// Generated by CoffeeScript 2.4.1
// export interface Node<T> {
//   left?: Node<T>
//   right?: Node<T>
//   up?: Node<T>
//   down?: Node<T>
//   col?: Column<T>
//   index?: number
//   data?: T
// }

// export interface Column<T> {
//   head: Node<T>
//   len: number
//   prev?: Column<T>
//   next?: Column<T>
// }

// export interface Row<T> {
//   coveredColumns: number[]
//   data: T
// }

// export interface Result<T> {
//   data: T
//   index: number
// }

// export type BinaryNumber = (0 | 1)

// export interface SearchConfig<T = any> {
//   numPrimary: number
//   numSecondary: number
//   numSolutions: number
//   rows: Row<T>[]
// }

// export interface SimpleConstraint<T = any> {
//   row: BinaryNumber[],
//   data: T
// }

// export interface ComplexConstraint<T = any> {
//   primaryRow: BinaryNumber[]
//   secondaryRow: BinaryNumber[],
//   data: T
// }

// isSimpleConstraint = (arg) -> return arg.row != undefined

// isComplexConstraint = (arg) -> return arg.primaryRow != undefined and arg.secondaryRow != undefined

//export type Constraint<T = any> = SimpleConstraint<T> | ComplexConstraint<T>


//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW50ZXJmYWNlcy5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsiY29mZmVlXFxpbnRlcmZhY2VzLmNvZmZlZSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUEiLCJzb3VyY2VzQ29udGVudCI6WyIjIGV4cG9ydCBpbnRlcmZhY2UgTm9kZTxUPiB7XHJcbiMgICBsZWZ0PzogTm9kZTxUPlxyXG4jICAgcmlnaHQ/OiBOb2RlPFQ+XHJcbiMgICB1cD86IE5vZGU8VD5cclxuIyAgIGRvd24/OiBOb2RlPFQ+XHJcbiMgICBjb2w/OiBDb2x1bW48VD5cclxuIyAgIGluZGV4PzogbnVtYmVyXHJcbiMgICBkYXRhPzogVFxyXG4jIH1cclxuXHJcbiMgZXhwb3J0IGludGVyZmFjZSBDb2x1bW48VD4ge1xyXG4jICAgaGVhZDogTm9kZTxUPlxyXG4jICAgbGVuOiBudW1iZXJcclxuIyAgIHByZXY/OiBDb2x1bW48VD5cclxuIyAgIG5leHQ/OiBDb2x1bW48VD5cclxuIyB9XHJcblxyXG4jIGV4cG9ydCBpbnRlcmZhY2UgUm93PFQ+IHtcclxuIyAgIGNvdmVyZWRDb2x1bW5zOiBudW1iZXJbXVxyXG4jICAgZGF0YTogVFxyXG4jIH1cclxuXHJcbiMgZXhwb3J0IGludGVyZmFjZSBSZXN1bHQ8VD4ge1xyXG4jICAgZGF0YTogVFxyXG4jICAgaW5kZXg6IG51bWJlclxyXG4jIH1cclxuXHJcbiMgZXhwb3J0IHR5cGUgQmluYXJ5TnVtYmVyID0gKDAgfCAxKVxyXG5cclxuIyBleHBvcnQgaW50ZXJmYWNlIFNlYXJjaENvbmZpZzxUID0gYW55PiB7XHJcbiMgICBudW1QcmltYXJ5OiBudW1iZXJcclxuIyAgIG51bVNlY29uZGFyeTogbnVtYmVyXHJcbiMgICBudW1Tb2x1dGlvbnM6IG51bWJlclxyXG4jICAgcm93czogUm93PFQ+W11cclxuIyB9XHJcblxyXG4jIGV4cG9ydCBpbnRlcmZhY2UgU2ltcGxlQ29uc3RyYWludDxUID0gYW55PiB7XHJcbiMgICByb3c6IEJpbmFyeU51bWJlcltdLFxyXG4jICAgZGF0YTogVFxyXG4jIH1cclxuXHJcbiMgZXhwb3J0IGludGVyZmFjZSBDb21wbGV4Q29uc3RyYWludDxUID0gYW55PiB7XHJcbiMgICBwcmltYXJ5Um93OiBCaW5hcnlOdW1iZXJbXVxyXG4jICAgc2Vjb25kYXJ5Um93OiBCaW5hcnlOdW1iZXJbXSxcclxuIyAgIGRhdGE6IFRcclxuIyB9XHJcblxyXG4jIGlzU2ltcGxlQ29uc3RyYWludCA9IChhcmcpIC0+IHJldHVybiBhcmcucm93ICE9IHVuZGVmaW5lZFxyXG5cclxuIyBpc0NvbXBsZXhDb25zdHJhaW50ID0gKGFyZykgLT4gcmV0dXJuIGFyZy5wcmltYXJ5Um93ICE9IHVuZGVmaW5lZCBhbmQgYXJnLnNlY29uZGFyeVJvdyAhPSB1bmRlZmluZWRcclxuXHJcbiNleHBvcnQgdHlwZSBDb25zdHJhaW50PFQgPSBhbnk+ID0gU2ltcGxlQ29uc3RyYWludDxUPiB8IENvbXBsZXhDb25zdHJhaW50PFQ+Il19
//# sourceURL=c:\github\2020\037-Queens-dlx\coffee\interfaces.coffee